server:
  port: 7005
# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath*:mybatis/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.ptw.pojo
logging:
  level:
    root: info
spring:
  #session: 
   # store-type: none
  thymeleaf: 
    cache: false
  datasource:
    url: jdbc:mysql://10.10.130.41:3306/iview?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: mysqladmin
    driver-class-name: com.mysql.jdbc.Driver
  #jackson: 
   # date-format: yyyy-MM-dd
  profiles: 
    active: dev
  redis:
    database: 3
    host: 10.10.170.153
    port: 6379
    password: null
    timeout: 1000 #连接超时（毫秒）
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）  
        max-wait: -1    #连接池最大阻塞等待时间（使用负值表示没有限制）  
        max-idle: 10    #连接池中的最大空闲连接 
        min-idle: 0     #连接池中的最小空闲连接 
---
spring:
  profiles: dev #开发环境
system-params: 
  imagePath: E://image//
  filePath: E://
---
spring:
  profiles: release #开发环境
system-params: 
  imagePath: /home/image/
  filePath: /home/file/
